# 项目相关配置
linkwechat:
  # 名称
  name: linkwe-auth
  # 版本
  version: 3.1.0
  # 版权年份
  copyrightYear: 2021

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8090
  port: 8880
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql