server:
  port: 6400

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:18080/xxl-job-admin
    accessToken: default_token
    executor:
      appname: linkwechat-scheduler
      address:
      ip: 127.0.0.1
      port: 18081
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

spring:
  application:
    name: linkwechat-scheduler
