# Tomcat
server:
  port: 8181
  servlet:
    # 应用的访问路径
    context-path: /file

# 项目相关配置
linkwechat:
  # 腾讯云存储
  file:
    #单个数据大小,单位MB
    maxFileSize: 50
    #总上传数据大小,单位MB
    maxRequestSize: 100
    #腾讯云对象存储
    object: tencentOss
    cos:
      secretId: AKIDQRCizIeUGl13vakkDQMH0VkjhPr1rBBv
      secretKey: e3D8oFetseC0f8OX9XeV7UcTDiyyQ8cr
      region: ap-nanjing
      bucketName: link-wechat-1251309172
      cosImgUrlPrefix: https://link-wechat-1251309172.cos.ap-nanjing.myqcloud.com/