server:
  port: 9400

xxl:
  job:
    admin:
      addresses: http://118.195.206.166:18080/xxl-job-admin/
    accessToken: default_token
    executor:
      appname: linkwechat-scheduler
      address:
      ip: 139.155.6.139
      port: 18081
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

spring:
  application:
    name: linkwechat-scheduler
