linkwechat:
  # 获取ip地址开关
  addressEnabled: true
  #扫码登陆url
  wecomeLoginUrl: https://open.work.weixin.qq.com/wwopen/sso/qrConnect?appid={0}&agentid={1}&redirect_uri=REDIRECT_URI&state=STATE
  taskFissionUrl: http://demo.linkwechat.cn/mobile/#/taskTreasure?taskId={} #任务宝链接配置
  baiduMapsAk: edGc5mIugVxx7lwUx9YpraKeWmExG64o #百度地图开发者ak
  guideCodeUrl: http://demo.linkwechat.cn/mobile/#/guideCode #导购码
  guideGroupUrl: http://demo.linkwechat.cn/mobile/#/storeCode #导购群码
  lostCustomerRedirectUrl: http://demo.linkwechat.cn/mobile/#/lostCustomers #客户流失
  authorizeUrl: https://open.weixin.qq.com/connect/oauth2/authorize #js sdk身份认证url，不变
  seasRedirectUrl: http://demo.linkwechat.cn/mobile/#/highSeas #客户公海链接
  sopTagRedirectUrl: http://demo.linkwechat.cn/mobile/#/task #群sop和老客标签建群链接

# Spring配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      url: jdbc:p6spy:mysql://cdb-gvebaa90.bj.tencentcdb.com:10179/lw_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
      username: root
      password: lwhf@2021##$$
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
      cluster:
        refresh:
          adaptive: true
  rabbitmq:
    host: 120.79.64.17
    port: 5672
    username: admin
    password: admin@123
    virtual-host: linkWeChat
    #publisher-confirm-type: correlated #消息确认机制
    listener:
      simple:
        acknowledge-mode: manual  #手动 ack
        default-requeue-rejected: true
        retry:
          enabled: true
          max-attempts: 3
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true


mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.linkwechat.**.domain


swagger:
  enabled: true
  pathMapping: /
  title: LinkWeChat业务接口
  description: LinkWeChat业务相关接口
  version: 3.0

feign:
  okhttp:
    enabled: false
  httpclient:
    enabled: true
  client:
    refresh-enabled: true

wecom:
  welcome-msg-default: 你好，我是LinkWechat运营。我将协助您完成工具配置上线。
  error-code-retry: -1,42001,42009,40082,40014
  mq:
    exchange:
      callback: Ex_CallBack
      sync: Ex_Sync
      auth-install-fanout: Ex_AuthInstallFanout
      delay: Ex_Delay
      app-msg: Ex_AppMsg
    route:
      callback: Rk_CallBack
      third-callback: Rk_Third_CallBack
      sync:
        group-chat: Rk_GroupChat
        wecustomer: Rk_Wecustomer
        group-tag: Rk_GroupTag
        we-moments: Rk_Moments
        user-depart: Rk_UserDepart
      delay-group-msg: Rk_DelayGroupMsg
      group-msg: Rk_GroupMsg
      app-msg: Rk_AppMsg
    queue:
      callback: Qu_CallBack
      third-callback: Qu_Third_CallBack
      sync:
        group-chat: Qu_GroupChat
        wecustomer: Qu_WeCustomer
        grouptag:  Qu_GroupTag
        we-moments: Qu_Moments
        user-depart: Qu_UserDepart
      delay-group-msg: Qu_DelayGroupMsg
      group-msg: Qu_GroupMsg
      app-msg: Qu_AppMsg
  serve:
    linkwe-wecom: linkwe-wecom
    linkwe-auth: linkwe-auth
    linkwe-file: linkwe-file
    linkwe-api: linkwe-api