# 项目相关配置
linkwechat:
  # 名称
  name: linkwe-auth
  # 版本
  version: 3.1.0
  # 版权年份
  copyrightYear: 2021

# 开发环境配置
server:
  port: 6880
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.linkwechat.**.domain
  type-handlers-package: com.linkwechat.common.handler.GenericTypeHandler

security:
  captcha:
    enabled: true
    type: math  